services:
  freepbx:
    # network_mode: "host"
    ports:
    - "8080:80"
    # - "5060-5060:5060-5060/udp"
    # - "8082:8082/tcp"
    # - "10000-10050:10000-10050/udp"
    build:
      context: .
      dockerfile: Dockerfile